import express from "express";
import { cancelOrder, confirmOrder, createOrder, deliverOrder, getAllOrders, getMyOrders, getSingleOrder, getUserOrders, updateOrderStatus } from "../controllers/orderController.js";
import { isAuthenticated } from "../middleware/isAuthenticated.js";
const router = express.Router();
router.post("/create", isAuthenticated, createOrder);
router.get("/my", isAuthenticated, getMyOrders);
router.get("/user/:id", getUserOrders);
router.get("/all-orders", getAllOrders);
router.get( "/:id", getSingleOrder );
router.put( "/confirm/:id", confirmOrder ); 
router.put( "/cancel/:id", cancelOrder );
router.put( "/status/:id", updateOrderStatus );
router.put( "/deliver/:id", deliverOrder );
export default router;
